import json


mesh_to_name = {
"Mesh": "browOuterUpLeft", 
"Mesh1": "browInnerUp",
"Mesh2": "browDownRight",
"Mesh3": "browDownLeft",
"Mesh4": "noseSneerRight",
"Mesh5": "noseSneerLeft",
"Mesh6": "mouthUpperUpRight",
"Mesh7": "mouthUpperUpLeft",
"Mesh8": "mouthStretchRight",
"Mesh9": "mouthStretchLeft",
"Mesh10": "mouthSmileRight",
"Mesh11": "eyeLookOutRight",
"Mesh12": "eyeLookOutLeft",
"Mesh13": "eyeLookInRight",
"Mesh14": "eyeLookInLeft",
"Mesh15": "eyeLookDownRight",
"Mesh16": "eyeLookDownLeft",
"Mesh17": "eyeBlinkRight",
"Mesh18": "eyeBlinkLeft",
"Mesh19": "cheekSquintRight",
"Mesh20": "cheekSquintLeft",
"Mesh21": "cheekPuff",
"Mesh22": "browOuterUpRight",
"Mesh23": "mouthDimpleRight",
"Mesh24": "mouthDimpleLeft",
"Mesh25": "mouthClose",
"Mesh26": "jawRight",
"Mesh27": "jawOpen",
"Mesh28": "jawLeft",
"Mesh29": "jawForward",
"Mesh30": "eyeWideRight",
"Mesh31": "eyeWideLeft",
"Mesh32": "eyeSquintRight",
"Mesh33": "eyeSquintLeft",
"Mesh34": "eyeLookUpRight",
"Mesh35": "eyeLookUpLeft",
"Mesh36": "mouthRollUpper",
"Mesh37": "mouthRollLower",
"Mesh38": "mouthRight",
"Mesh39": "mouthPucker",
"Mesh40": "mouthPressRight", 
"Mesh41": "mouthPressLeft",
"Mesh42": "mouthLowerDownRight",
"Mesh43": "mouthLowerDownLeft",
"Mesh44": "mouthLeft",
"Mesh45": "mouthFunnel",
"Mesh46": "mouthFrownRight",
"Mesh47": "mouthFrownLeft",
"Mesh48": "mouthSmileLeft",
"Mesh49": "mouthShrugUpper",
"Mesh50": "mouthShrugLower"
}
name_to_mesh = {
"mouthLowerDownRight": "Mesh42", 
"noseSneerRight": "Mesh4", 
"eyeWideRight": "Mesh30", 
"browInnerUp": "Mesh1", 
"eyeSquintRight": "Mesh32", 
"mouthClose": "Mesh25", 
"jawOpen": "Mesh27", 
"browDownRight": "Mesh2", 
"mouthShrugUpper": "Mesh49", 
"cheekPuff": "Mesh21", 
"mouthFunnel": "Mesh45", 
"mouthStretchLeft": "Mesh9", 
"eyeLookDownRight": "Mesh15", 
"mouthRollUpper": "Mesh36", 
"mouthUpperUpRight": "Mesh6", 
"mouthPressLeft": "Mesh41", 
"noseSneerLeft": "Mesh5", 
"eyeLookDownLeft": "Mesh16", 
"mouthUpperUpLeft": "Mesh7", 
"mouthShrugLower": "Mesh50",
"eyeLookUpLeft": "Mesh35", 
"mouthLowerDownLeft": "Mesh43", 
"cheekSquintRight": "Mesh19", 
"eyeLookInLeft": "Mesh14", 
"eyeLookInRight": "Mesh13", 
"mouthLeft": "Mesh44", 
"jawForward": "Mesh29", 
"browOuterUpRight": "Mesh22", 
"mouthPressRight": "Mesh40", 
"browDownLeft": "Mesh3", 
"cheekSquintLeft": "Mesh20", 
"eyeLookUpRight": "Mesh34", 
"mouthSmileLeft": "Mesh48", 
"jawRight": "Mesh26", 
"mouthPucker": "Mesh39", 
"jawLeft": "Mesh28", 
"mouthSmileRight": "Mesh10",
"eyeBlinkLeft": "Mesh18", 
"mouthDimpleLeft": "Mesh24", 
"eyeLookOutLeft": "Mesh12", 
"mouthDimpleRight": "Mesh23", 
"eyeWideLeft": "Mesh31", 
"eyeLookOutRight": "Mesh11", 
"mouthStretchRight": "Mesh8", 
"browOuterUpLeft": "Mesh", 
"mouthFrownLeft": "Mesh47", 
"mouthFrownRight": "Mesh46", 
"eyeBlinkRight": "Mesh17", 
"mouthRight": "Mesh38", 
"mouthRollLower": "Mesh37",
"eyeSquintLeft": "Mesh33"
}
new_name_to_mesh = {}
for key in name_to_mesh:
    new_name_to_mesh[key.lower()] = name_to_mesh[key]
new_mesh_to_name = {}
for key in mesh_to_name:
    new_mesh_to_name[key] = mesh_to_name[key].lower()
with open('C:/Users/evansamaa/Desktop/Staggered_faces/models/mesh_number_to_AU_name.json', 'w') as fp:
    json.dump(new_mesh_to_name, fp)
with open('C:/Users/evansamaa/Desktop/Staggered_faces/models/AU_name_to_mesh_number.json', 'w') as fp:
    json.dump(new_name_to_mesh, fp)